# Generated by Django 4.2.7 on 2025-09-02 13:21

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        VectorExtension(),
    ]
