# Generated by Django 4.2.7 on 2025-09-02 13:21

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Narrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('emergence', 'Narrative Emergence'), ('shift', 'Narrative Shift'), ('peak', 'Narrative Peak'), ('decline', 'Narrative Decline')], max_length=20)),
                ('description', models.TextField()),
                ('event_date', models.DateTimeField()),
                ('significance_score', models.FloatField(default=0.0)),
                ('narrative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='narratives.narrative')),
                ('related_articles', models.ManyToManyField(blank=True, to='articles.article')),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='NarrativeCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cluster_date', models.DateField()),
                ('centroid', pgvector.django.VectorField(blank=True, dimensions=768, null=True)),
                ('articles', models.ManyToManyField(to='articles.article')),
                ('narrative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='narratives.narrative')),
            ],
            options={
                'ordering': ['-cluster_date'],
            },
        ),
    ]
