# Generated by Django 4.2.7 on 2025-09-03 19:30

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_url'),
        ('narratives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='narrative',
            name='coherence_score',
            field=models.FloatField(default=0.0, help_text='Average cosine similarity within cluster'),
        ),
        migrations.AddField(
            model_name='narrative',
            name='near_duplicate_rate',
            field=models.FloatField(default=0.0, help_text='Rate of near-duplicate content'),
        ),
        migrations.AddField(
            model_name='narrative',
            name='persistence_days',
            field=models.IntegerField(default=0, help_text='Number of days narrative persisted'),
        ),
        migrations.AddField(
            model_name='narrative',
            name='source_diversity_score',
            field=models.FloatField(default=0.0, help_text='Entropy-based diversity of sources'),
        ),
        migrations.AddField(
            model_name='narrative',
            name='support_count',
            field=models.IntegerField(default=0, help_text='Number of supporting statements/articles'),
        ),
        migrations.AddField(
            model_name='narrative',
            name='unique_sources_count',
            field=models.IntegerField(default=0, help_text='Number of unique domains'),
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(help_text='Who is making the statement or performing the action', max_length=300)),
                ('action', models.TextField(help_text='What is being said or done')),
                ('reason', models.TextField(blank=True, help_text='Why - the reasoning or cause')),
                ('consequence', models.TextField(blank=True, help_text='Expected or stated outcome/consequence')),
                ('full_statement', models.TextField(help_text='Complete extracted statement text')),
                ('embedding', pgvector.django.VectorField(blank=True, dimensions=768, null=True)),
                ('confidence_score', models.FloatField(default=0.0, help_text='LLM confidence in extraction (0-1)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='articles.article')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='narrativecluster',
            name='statements',
            field=models.ManyToManyField(blank=True, help_text='Clustered statements that form this narrative', to='narratives.statement'),
        ),
    ]
